# Secret for reth JWT authentication
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reth.fullname" . }}-secrets
  labels:
    {{- include "reth.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret.txt: {{ .Values.secrets.jwtSecret | default "eb641c4c6f2cc0b526cf35ba7b29ebe37e98b47f52fccea3f9b715b1ca77f391" | quote }}
