# JWT secret for op-geth engine API authentication
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-geth.fullname" . }}-secrets
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt.hex: {{ .Values.secrets.jwtSecret | default "eb641c4c6f2cc0b526cf35ba7b29ebe37e98b47f52fccea3f9b715b1ca77f391" | quote }}

