{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sqlit.fullname" . }}-miner
  labels:
    {{- include "sqlit.minerLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sqlit.minerSelectorLabels" . | nindent 6 }}
{{- end }}
