apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sqlit.fullname" . }}
  labels:
    {{- include "sqlit.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sqlit.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sqlit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sqlit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: sqlit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SQLIT_ROLE
              value: blockproducer
            - name: METRIC_WEB_ADDR
              value: "0.0.0.0:4665"
          ports:
            - name: api
              containerPort: 4661
              protocol: TCP
            - name: metrics
              containerPort: 4665
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /app/data
          {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
