apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "messaging.fullname" . }}-config
  labels:
    {{- include "messaging.labels" . | nindent 4 }}
data:
  environment: {{ .Values.global.environment }}
  domain: {{ .Values.global.domain }}
  keyRegistryAddress: {{ .Values.relay.config.keyRegistryAddress | default "" | quote }}
  nodeRegistryAddress: {{ .Values.relay.config.nodeRegistryAddress | default "" | quote }}
  sqlitNodes: {{ .Values.relay.config.sqlitNodes | default "" | quote }}
  sqlitDatabaseId: {{ .Values.relay.config.sqlitDatabaseId | quote }}
  jejuRpcUrl: {{ .Values.relay.config.jejuRpcUrl | quote }}
  ipfsGateway: {{ .Values.relay.config.ipfsGateway | quote }}
  farcasterHubUrl: {{ .Values.farcasterSync.config.hubUrl | quote }}

